# Generated by Django 5.1 on 2024-08-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table", models.CharField(max_length=100)),
                ("time", models.TimeField()),
                ("date", models.DateField()),
                ("accomodation", models.IntegerField()),
            ],
        ),
    ]
